#!/bin/bash

# define standard colors
cGREEN=`tput -Txterm setaf 2`
cWHITE=`tput -Txterm setaf 7`
cRESET=`tput -Txterm sgr0`

# Print menu title
printTitle()
{
	echo -e "${cGREEN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"	
	echo "$1"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo -e ${cWHITE}
}

# Wait for user to proceed 
showReport()
{
    clear
    printTitle "    T I M E - M A C H I N E "
    echo -e "I started at: \n\t$tickStart"
    printf "\nI ran for: \n\t%s\n" `calculateHours $SECONDS`
    echo ""
    read -p "Press [Enter] key to exit..." fackEnterKey
    exit 0
}

calculateHours()
{
    ((h=${1}/3600))
    ((m=(${1}%3600)/60))
    ((s=${1}%60))

    printf "%02d:%02d:%02d" "$h" "$m" "$s"
}

# Trap CTRL+C, CTRL+Z and quit singles
trap showReport SIGINT SIGQUIT SIGTSTP

tickStart=`date '+%d/%m/%y %H:%M:%S'`

# Main loop
while true
do
    clear
    printTitle "    T I M E - M A C H I N E "
    echo -e "I'm running since: \n\t$tickStart"
    printf "\nTime elapsed: \n\t%s\n" `calculateHours $SECONDS`
    sleep 1
done